### ISSUE TITLE
Suggestion: Work with LuckPerms

### ISSUE THREAD

**Issue by TheCodingGorilla** [okx-code/DeathBan#2]
Loving this plugin!

I would love for Ranks to be powered by LP and maximum lives to be changed based on rank.

**Comment by okx-code** [comment]
This plugin already supports LuckPerms via Vault.

**Comment by TheCodingGorilla** [comment]
Any chance you could give some guidance on how to do this? The LuckPerms guys weren't able to help.

I've tried using `deathban.groups.<luckperm-group-name>` but that hasn't worked.

I've also given the permission of `deathban.groups.<luckperm-group-name>` to the group within LuckPerms.

Tried all variations I could think of but only the `ops` are taking the max life count.

**Comment by okx-code** [comment]
You setup the groups in config.yml and set the permissions to be in those groups yourselves. They are not related to LuckPerms' groups.

**Comment by TheCodingGorilla** [comment]
Great! It works as explained.
